---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: priyanka
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: priyanka9288/backend
        imagePullPolicy: Always
        env:
           - name: POSTGRES_HOST
            value: postgresql-svc:5432
          - name: POSTGRES_PORT
           value: "5432"
          - name: POSTGRES_DB
           value: myapp
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /ok
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: priyanka
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
  selector:
   role: api