---
apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: priyanka
 name: postgresdb
spec:
 replicas: 1
 selector:
   matchLabels:
     app: postgresdb
 template:
   metadata:
     labels:
       app: postgresdb
   spec:
     containers:
     - name: postgresdb
       image: postgres:14.1
       ports:
       - containerPort: 5432
       env:
       - name: POSTGRES_USER
         valueFrom:
           secretKeyRef:
             name: postgres-secrets
             key: username
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: postgres-secrets
             key: password
       - name: POSTGRES_DB
         value: mydb
       resources:
         requests:
           memory: 512Mi
           cpu: 250m
         limits:
           memory: 1Gi
           cpu: 500m

---
apiVersion: v1
kind: Secret
metadata:
 namespace: priyanka
 name: postgres-secrets
type: Opaque
data:
 username: YWRtaW4=
 password: cGFzc3dvcmQxMjM=

---
apiVersion: v1
kind: Service
metadata:
 namespace: priyanka
 name: postgres-svc
spec:
 selector:
   app: postgresdb
 ports:
 - name: postgres
   port: 5432
   targetPort: 5432