---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: srinu
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: nasrinivas/frontend:12
        imagePullPolicy: Always
        env:
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: srinu
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
   role: frontend